app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=False)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from flask import render_template, Response, flash
from werkzeug.exceptions import abort
from app.main import main_bp
from app.main.camera import Camera
from source.video_detector import detect_violation
from source.video_detector import print_notif
import winsound

import json
import time

sub = cv2.createBackgroundSubtractorMOG2()

@main_bp.route("/")
def home_page():
    return render_template("live_detection.html")


@main_bp.route("/live")
def live_detect():
  return render_template("live_detection.html")

@main_bp.route("/video")
def video_detect():
  return render_template("video_detection.html")


def gen(camera):
    while True:
        frame = camera.get_frame()
        frame_processed = detect_violation(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')

def genn():
    cap = cv2.VideoCapture('videotester2.avi')

    while(cap.isOpened()):
      ret, frame = cap.read()
      if ret:
        frame = detect_violation(frame)
        frame = cv2.imencode('.jpg', frame)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
      key = cv2.waitKey(20)
      if key == 27:
            break


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')

#stream local files
@main_bp.route("/streamread")
def streamread():
  return Response(genn(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good

@main_bp.route("/listen")
def listen():

  def respond_to_client():
    while True:
      global counter
      global statusNotif
      statusNotif = print_notif()
    #   print(statusNotif)
      color = "white"
    #   with open("color.txt", "r") as f:
    #     color = f.read()
    #     print("**")
      if(color == "white"):
        # print(counter)
        # counter += 1
        _data = json.dumps({"color":color, "counter":statusNotif})
        yield f"id: 1\ndata: {_data}\nevent: online\n\n"
      time.sleep(0.5)
  return Response(respond_to_client(), mimetype='text/event-stream')



      




        

app/templates/backups.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SDMS</title>
<!-- add icon link -->
<link rel="icon" href="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" type="image/x-icon">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/adminlte.min.css') }}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" 
            integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" >
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="#" class="navbar-brand">
        <img src="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" alt="PNJ Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Social Distance Monitoring</span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        
        <!-- Notifications Dropdown Menu -->
        
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <!-- <i class="fas fa-th-large"></i> -->
            <i>Home</i>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
              <!-- <i class="fas fa-th-large"></i> -->
              <i>Live Detection</i>
            </a>
          </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Top Navigation</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container">
        
        <div class="card card-primary card-outline">
          <div class="card-header">
            <h4 class="card-title">Form Detection</h4>
            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
          </div>
          <div class="card-body text-center">
          <img id="img-target" class="img-fluid mx-auto d-block" src="{{ url_for('static', filename='dist/img/socialdistance.jpg') }}" width="500" height="300" alt="Photo">  

          </div>
          <!-- /.card-body -->
          <div class="card-footer text-center">
          <button id="start" onclick="start()" type="button" class="btn btn-outline-primary">Start Detecting</button>
          |||
          <button id="stop" onclick="stop()" type="button" class="btn btn-outline-danger">Stop Detecting</button>
          </div>
          </div>
          <!-- /.card-footer-->

        </div>
        <br>
      </div><!-- /.container-fluid -->
    </div>
    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer text-center">
    <!-- Default to the left -->
    <strong><small>Developed with</small> &hearts; <small>by Waheed Khoi.</small></strong>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<!-- <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

{% block custom_js %}
<script>
    $(document).ready(function(){
        // toastr.error('more than 2 people !');
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
        document.querySelector("#counter").innerText = "2";
    })
    
        function stop(){
            $("#img-target").attr("src", "/static/images/socialdistance.jpg");
            $("#stop").attr("class","btn btn-danger active");
    
            $("#start").attr("class","btn btn-outline-primary");
            document.querySelector("#counter").innerText = "2";
        }
        function start(){
            $("#img-target").attr("src", "{{url_for('main.video_feed')}}");
            $("#start").attr("class","btn btn-primary active");
    
            $("#stop").attr("class","btn btn-outline-danger");
            document.querySelector("#counter").innerText = "0";
        }
        
        var eventSource = new EventSource("/listen")
        var waitings = false;
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }
        eventSource.addEventListener("message", function(e) {
          console.log(e.data)
        }, true)
    
        eventSource.addEventListener("online", function(e) {
          // console.log(e.data.color)
          var checkStop = document.querySelector("#counter").innerText;
          console.log(checkStop);
          if (checkStop == "2")
          {
              data.counter = "0";
          }
          else{
            data = JSON.parse(e.data)
            document.querySelector("#counter").innerText = data.counter
            document.querySelector("body").style.backgroundColor= data.color
          }
          if (data.counter == "1"){
            toastr.error('more than 2 people !');
            // toastr.warning('asdasd <img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:50px;">', 'Toast Image');
            // toastr.info('<img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:150px;">', 'Toast Image')
          }
          else{
            // sleep(5000).then(() => { toastr.clear(); });
            console.log('tidak lebih dari 2');
          }
        }, true)
    </script>
    
    <script>
        toastr.options = {
      "closeButton": false,
      "debug": false,
      "newestOnTop": true,
      "progressBar": false,
      "positionClass": "toast-top-full-width",
      "preventDuplicates": true,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
        }
    </script>
{% endblock %}
</body>
</html>

app/templates/based.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SDMS</title>
<!-- add icon link -->
<link rel="icon" href="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" type="image/x-icon">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/adminlte.min.css') }}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" 
            integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" >
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="#" class="navbar-brand">
        <img src="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" alt="PNJ Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Social Distance Monitoring</span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        
        <!-- Notifications Dropdown Menu -->
        
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ url_for('main.live_detect') }}" role="button">
            <!-- <i class="fas fa-th-large"></i> -->
            <i>Live Detection</i>
          </a>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ url_for('main.video_detect') }}" role="button">
              <i>Video Detection</i>
            </a>
          </li> -->
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Top Navigation</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <br>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

<!-- Main Footer -->
<footer class="main-footer text-center">
  <!-- Default to the left -->
  <strong><small>Developed with</small> &hearts; <small>by Waheed Khoi.</small></strong>
</footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<!-- <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"></script>

      {% block custom_js %}
      {% endblock %}      
</body>
</html>            

app/templates/dashboard.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SDMS</title>
<!-- add icon link -->
<link rel="icon" href="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" type="image/x-icon">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/adminlte.min.css') }}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" 
            integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" >
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="#" class="navbar-brand">
        <img src="{{ url_for('static', filename='dist/img/pnj_logo.png') }}" alt="PNJ Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Social Distance Monitoring</span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        
        <!-- Notifications Dropdown Menu -->
        
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <!-- <i class="fas fa-th-large"></i> -->
            <i>Live Detection</i>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
              <!-- <i class="fas fa-th-large"></i> -->
              <i>Video Detection</i>
            </a>
          </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Top Navigation</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container">
        
        <div class="card card-primary card-outline">
          <div class="card-header">
            <h4 class="card-title">Form Detection</h4>
            {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}
            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
          </div>
          <div class="card-body text-center">
            <div hidden="true" id="counter"></div>
          <img id="img-target" class="img-fluid mx-auto d-block" src="{{ url_for('static', filename='dist/img/socialdistance.jpg') }}" width="700" height="600">  

          </div>
          <!-- /.card-body -->
          <div class="card-footer text-center">
          <button id="start" onclick="start()" type="button" class="btn btn-outline-primary">Start Detecting</button>
          |||
          <button id="stop" onclick="stop()" type="button" class="btn btn-outline-danger">Stop Detecting</button>
          </div>
          </div>
          <!-- /.card-footer-->

        </div>
        <br>
      </div><!-- /.container-fluid -->
    </div>
    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer text-center">
    <!-- Default to the left -->
    <strong><small>Developed with</small> &hearts; <small>by Waheed Khoi.</small></strong>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<!-- <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>


<script>
    $(document).ready(function(){
        // toastr.error('more than 2 people !');
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
        document.querySelector("#counter").innerText = "2";
    })
    
        function stop(){
            $("#img-target").attr("src", "/static/images/socialdistance.jpg");
            $("#stop").attr("class","btn btn-danger active");
    
            $("#start").attr("class","btn btn-outline-primary");
            document.querySelector("#counter").innerText = "2";
        }
        function start(){
            $("#img-target").attr("src", "{{url_for('main.video_feed')}}");
            $("#start").attr("class","btn btn-primary active");
    
            $("#stop").attr("class","btn btn-outline-danger");
            document.querySelector("#counter").innerText = "0";
        }
        
        var eventSource = new EventSource("/listen")
        var waitings = false;
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }
        eventSource.addEventListener("message", function(e) {
          console.log(e.data)
        }, true)
    
        eventSource.addEventListener("online", function(e) {
          // console.log(e.data.color)
          var checkStop = document.querySelector("#counter").innerText;
          console.log(checkStop);
          if (checkStop == "2")
          {
              data.counter = "0";
          }
          else{
            data = JSON.parse(e.data)
            document.querySelector("#counter").innerText = data.counter
            document.querySelector("body").style.backgroundColor= data.color
          }
          if (data.counter == "1"){
            toastr.error('Pelanggaran Jarak Aman!');
            // toastr.warning('asdasd <img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:50px;">', 'Toast Image');
            // toastr.info('<img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:150px;">', 'Toast Image')
          }
          else{
            // sleep(5000).then(() => { toastr.clear(); });
            console.log('--');
          }
        }, true)
    </script>
    
    <script>
        toastr.options = {
      "closeButton": false,
      "debug": false,
      "newestOnTop": true,
      "progressBar": false,
      "positionClass": "toast-top-full-width",
      "preventDuplicates": true,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
        }
    </script>
</body>
</html>

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}